# Generated by Django 3.2.6 on 2021-08-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('en_app', '0006_en_editorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='en_article',
            name='photo_img',
            field=models.ImageField(blank=True, default='0', null=True, upload_to='photos/english/en_article'),
        ),
        migrations.AlterField(
            model_name='en_editorial',
            name='photo_img',
            field=models.ImageField(blank=True, default='0', null=True, upload_to='photos/english/en_editorial'),
        ),
        migrations.AlterField(
            model_name='en_interview',
            name='photo_img',
            field=models.ImageField(blank=True, default='0', null=True, upload_to='photos/english/en_interview'),
        ),
        migrations.AlterField(
            model_name='en_main_news',
            name='photo_img',
            field=models.ImageField(blank=True, default='0', null=True, upload_to='photos/english/en_news'),
        ),
        migrations.AlterField(
            model_name='en_news',
            name='photo_img',
            field=models.ImageField(blank=True, default='0', null=True, upload_to='photos/english/en_news'),
        ),
        migrations.AlterField(
            model_name='en_sports',
            name='photo_img',
            field=models.ImageField(blank=True, default='0', null=True, upload_to='photos/english/en_sports'),
        ),
    ]
