# Generated by Django 3.2.6 on 2021-09-01 06:03

import ckeditor.fields
import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('en_app', '0007_auto_20210831_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='en_latest_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('photo_img', models.ImageField(default='0', upload_to='photos/english/en_latest_news')),
                ('news_summary', django_mysql.models.SizedTextField(null=True, size_class=2)),
                ('description', ckeditor.fields.RichTextField(default='')),
                ('date_uploaded', models.DateField(default=datetime.datetime.now)),
                ('time_uploaded', models.TimeField(default=datetime.datetime.now)),
                ('number_of_views', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'en_latest_news',
            },
        ),
        migrations.AlterField(
            model_name='en_article',
            name='photo_img',
            field=models.ImageField(default='0', upload_to='photos/english/en_article'),
        ),
        migrations.AlterField(
            model_name='en_editorial',
            name='photo_img',
            field=models.ImageField(default='0', upload_to='photos/english/en_editorial'),
        ),
        migrations.AlterField(
            model_name='en_interview',
            name='photo_img',
            field=models.ImageField(default='0', upload_to='photos/english/en_interview'),
        ),
        migrations.AlterField(
            model_name='en_main_news',
            name='photo_img',
            field=models.ImageField(default='0', upload_to='photos/english/en_main_news'),
        ),
        migrations.AlterField(
            model_name='en_news',
            name='photo_img',
            field=models.ImageField(default='0', upload_to='photos/english/en_news'),
        ),
        migrations.AlterField(
            model_name='en_sports',
            name='photo_img',
            field=models.ImageField(default='0', upload_to='photos/english/en_sports'),
        ),
    ]
