# Generated by Django 3.2.6 on 2021-09-01 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('en_app', '0008_auto_20210901_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='en_latest_news',
            name='date_time_picker',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='en_latest_news',
            name='news_type',
            field=models.CharField(default='en_latest_news', max_length=20),
        ),
    ]
