# Generated by Django 3.2.6 on 2021-08-12 11:27

import datetime
from django.db import migrations, models
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=20)),
            ],
            options={
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='admin_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'admin_user',
            },
        ),
        migrations.CreateModel(
            name='antarastriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('photo_img', models.CharField(max_length=100)),
                ('description', django_mysql.models.SizedTextField(size_class=3)),
                ('time_uploaded', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'antarastriya',
            },
        ),
        migrations.CreateModel(
            name='antarbarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('photo_img', models.CharField(max_length=100)),
                ('description', django_mysql.models.SizedTextField(size_class=3)),
                ('time_uploaded', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'antarbarta',
            },
        ),
        migrations.CreateModel(
            name='Breaking_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('time_uploaded', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Breakin_news',
            },
        ),
        migrations.CreateModel(
            name='esthaniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('photo_img', models.CharField(max_length=100)),
                ('description', django_mysql.models.SizedTextField(size_class=3)),
                ('time_uploaded', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'esthaniya',
            },
        ),
        migrations.CreateModel(
            name='khelud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('photo_img', models.CharField(max_length=100)),
                ('description', django_mysql.models.SizedTextField(size_class=3)),
                ('time_uploaded', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'khelud',
            },
        ),
        migrations.CreateModel(
            name='Latest_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('photo_img', models.CharField(max_length=100)),
                ('description', django_mysql.models.SizedTextField(size_class=3)),
                ('time_uploaded', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Latest_news',
            },
        ),
        migrations.CreateModel(
            name='Main_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('photo_img', models.CharField(max_length=100)),
                ('description', django_mysql.models.SizedTextField(size_class=3)),
                ('time_uploaded', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Main_news',
            },
        ),
        migrations.CreateModel(
            name='news_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('thoughts', models.CharField(max_length=200)),
                ('url', models.CharField(default=None, max_length=200)),
                ('time_uploaded', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'news_comment',
            },
        ),
        migrations.CreateModel(
            name='sandhiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('photo_img', models.CharField(max_length=100)),
                ('description', django_mysql.models.SizedTextField(size_class=3)),
                ('time_uploaded', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'sandhiya',
            },
        ),
        migrations.CreateModel(
            name='suchanapraviti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('photo_img', models.CharField(max_length=100)),
                ('description', django_mysql.models.SizedTextField(size_class=3)),
                ('time_uploaded', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'suchanapraviti',
            },
        ),
        migrations.CreateModel(
            name='youtubelink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('time_uploaded', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'youtubelink',
            },
        ),
    ]
