# Generated by Django 3.2.6 on 2021-08-12 14:24

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manoranjan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('photo_img', models.CharField(max_length=100)),
                ('description', django_mysql.models.SizedTextField(size_class=3)),
                ('time_uploaded', models.DateField(default=datetime.datetime.now)),
                ('news_type', models.CharField(default='manoranjan', max_length=20)),
            ],
            options={
                'db_table': 'manoranjan',
            },
        ),
        migrations.CreateModel(
            name='pradesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('photo_img', models.CharField(max_length=100)),
                ('description', django_mysql.models.SizedTextField(size_class=3)),
                ('time_uploaded', models.DateField(default=datetime.datetime.now)),
                ('news_type', models.CharField(default='pradesh', max_length=20)),
            ],
            options={
                'db_table': 'pradesh',
            },
        ),
        migrations.AddField(
            model_name='esthaniya',
            name='news_type',
            field=models.CharField(default='esthaniya', max_length=20),
        ),
        migrations.AddField(
            model_name='khelud',
            name='news_type',
            field=models.CharField(default='khelud', max_length=20),
        ),
        migrations.AddField(
            model_name='sandhiya',
            name='news_type',
            field=models.CharField(default='sandhiya', max_length=20),
        ),
    ]
