# Generated by Django 3.2.6 on 2021-08-12 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210812_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandhiya',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sandhiya',
            name='time_uploaded',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
