# Generated by Django 3.2.6 on 2021-08-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210812_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antarbarta',
            name='photo_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/antarbarta'),
        ),
        migrations.AlterField(
            model_name='esthaniya',
            name='photo_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/esthaniya'),
        ),
        migrations.AlterField(
            model_name='khelud',
            name='photo_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/khelud'),
        ),
        migrations.AlterField(
            model_name='manoranjan',
            name='photo_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/manoranjan'),
        ),
    ]
