# Generated by Django 3.2.6 on 2021-08-13 15:31

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210813_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='bichar_lekh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('photo_img', models.ImageField(blank=True, null=True, upload_to='photos/bichar_lekh')),
                ('news_summary', models.CharField(max_length=300, null=True)),
                ('description', django_mysql.models.SizedTextField(size_class=3)),
                ('date_uploaded', models.DateField(default=datetime.datetime.now)),
                ('time_uploaded', models.TimeField(default=datetime.datetime.now)),
                ('news_type', models.CharField(default='bichar_lekh', max_length=20)),
            ],
            options={
                'db_table': 'bichar_lekh',
            },
        ),
    ]
