# Generated by Django 3.2.6 on 2021-08-14 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_sampadakiya'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime.now, help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
        migrations.AddField(
            model_name='admin_user',
            name='time_uploaded',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
