# Generated by Django 3.2.6 on 2021-08-14 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210814_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_user',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
