# Generated by Django 3.2.6 on 2021-08-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_admin_user_date_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_user',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='admin_user',
            name='time_uploaded',
        ),
    ]
