# Generated by Django 3.2.6 on 2021-08-14 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210814_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breaking_news',
            name='editor_name',
        ),
        migrations.AddField(
            model_name='breaking_news',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='breaking_news',
            name='time_uploaded',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
