# Generated by Django 3.2.6 on 2021-08-15 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210814_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubelink',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='youtubelink',
            name='time_uploaded',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
