# Generated by Django 3.2.6 on 2021-08-16 12:55

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210815_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antarastriya',
            name='news_summary',
            field=django_mysql.models.SizedTextField(null=True, size_class=2),
        ),
        migrations.AlterField(
            model_name='antarbarta',
            name='news_summary',
            field=django_mysql.models.SizedTextField(null=True, size_class=2),
        ),
        migrations.AlterField(
            model_name='bichar_lekh',
            name='news_summary',
            field=django_mysql.models.SizedTextField(null=True, size_class=2),
        ),
        migrations.AlterField(
            model_name='esthaniya',
            name='news_summary',
            field=django_mysql.models.SizedTextField(null=True, size_class=2),
        ),
        migrations.AlterField(
            model_name='grihaprista',
            name='news_summary',
            field=django_mysql.models.SizedTextField(null=True, size_class=2),
        ),
        migrations.AlterField(
            model_name='khelud',
            name='news_summary',
            field=django_mysql.models.SizedTextField(null=True, size_class=2),
        ),
        migrations.AlterField(
            model_name='manoranjan',
            name='news_summary',
            field=django_mysql.models.SizedTextField(null=True, size_class=2),
        ),
        migrations.AlterField(
            model_name='pradesh',
            name='news_summary',
            field=django_mysql.models.SizedTextField(null=True, size_class=2),
        ),
        migrations.AlterField(
            model_name='sampadakiya',
            name='news_summary',
            field=django_mysql.models.SizedTextField(null=True, size_class=2),
        ),
        migrations.AlterField(
            model_name='sandhiya',
            name='news_summary',
            field=django_mysql.models.SizedTextField(null=True, size_class=2),
        ),
        migrations.AlterField(
            model_name='suchanapraviti',
            name='news_summary',
            field=django_mysql.models.SizedTextField(null=True, size_class=2),
        ),
    ]
