# Generated by Django 3.2.6 on 2021-08-17 05:40

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210816_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_news',
            name='news_summary',
            field=django_mysql.models.SizedTextField(null=True, size_class=2),
        ),
        migrations.AlterField(
            model_name='latest_news',
            name='photo_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/Latest_news'),
        ),
    ]
