# Generated by Django 3.2.6 on 2021-08-19 05:26

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210817_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user',
            name='authorization',
            field=models.CharField(default='All', max_length=10),
        ),
        migrations.AddField(
            model_name='admin_user',
            name='contact',
            field=models.CharField(default='***', max_length=20),
        ),
        migrations.AlterField(
            model_name='sandhiya',
            name='description',
            field=django_mysql.models.SizedTextField(null=True, size_class=3),
        ),
    ]
