# Generated by Django 3.2.6 on 2021-08-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210819_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user',
            name='user_name',
            field=models.CharField(default='user', max_length=20, unique=True),
        ),
    ]
