# Generated by Django 3.2.6 on 2021-08-20 05:08

import ckeditor.fields
from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210820_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='esthaniya',
            name='news_summary',
            field=django_mysql.models.SizedTextField(null=True, size_class=2),
        ),
        migrations.AddField(
            model_name='khelud',
            name='description',
            field=ckeditor.fields.RichTextField(default='enter news'),
        ),
        migrations.AddField(
            model_name='manoranjan',
            name='description',
            field=ckeditor.fields.RichTextField(default='enter news'),
        ),
        migrations.AddField(
            model_name='pradesh',
            name='description',
            field=ckeditor.fields.RichTextField(default='enter news'),
        ),
        migrations.AddField(
            model_name='sandhiya',
            name='description',
            field=ckeditor.fields.RichTextField(default='enter news'),
        ),
        migrations.AlterField(
            model_name='esthaniya',
            name='description',
            field=ckeditor.fields.RichTextField(default='enter news'),
        ),
    ]
