# Generated by Django 3.2.6 on 2021-08-20 05:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210820_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='grihaprista',
            name='description',
            field=ckeditor.fields.RichTextField(default='enter news'),
        ),
        migrations.AddField(
            model_name='latest_news',
            name='description',
            field=ckeditor.fields.RichTextField(default='enter news'),
        ),
    ]
