# Generated by Django 3.2.6 on 2021-08-21 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210820_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antarastriya',
            name='description',
        ),
        migrations.RemoveField(
            model_name='antarbarta',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bichar_lekh',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sampadakiya',
            name='description',
        ),
        migrations.RemoveField(
            model_name='suchanapraviti',
            name='description',
        ),
    ]
