# Generated by Django 3.2.6 on 2021-08-24 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210822_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='esthaniya',
            name='date_picker',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='esthaniya',
            name='time_picker',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='khelud',
            name='date_picker',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='khelud',
            name='time_picker',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='manoranjan',
            name='date_picker',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='manoranjan',
            name='time_picker',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='pradesh',
            name='date_picker',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='pradesh',
            name='time_picker',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sandhiya',
            name='date_picker',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sandhiya',
            name='time_picker',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
