# Generated by Django 3.2.6 on 2021-08-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210824_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='antarastriya',
            name='number_of_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='antarbarta',
            name='number_of_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bichar_lekh',
            name='number_of_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='esthaniya',
            name='number_of_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grihaprista',
            name='number_of_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='khelud',
            name='number_of_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='latest_news',
            name='number_of_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manoranjan',
            name='number_of_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pradesh',
            name='number_of_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampadakiya',
            name='number_of_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sandhiya',
            name='number_of_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suchanapraviti',
            name='number_of_views',
            field=models.BigIntegerField(default=0),
        ),
    ]
