# Generated by Django 3.2.6 on 2021-08-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20210824_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user',
            name='fullname',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='admin_user',
            name='photo_img',
            field=models.ImageField(blank=True, default='photos/guest-user.jpg', null=True, upload_to='photos/Latest_news'),
        ),
    ]
