# Generated by Django 3.2.6 on 2021-08-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20210825_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_user',
            name='photo_img',
            field=models.ImageField(blank=True, default='photos/guest-user.jpg', null=True, upload_to='photos/admin_user'),
        ),
    ]
