# Generated by Django 3.2.6 on 2021-08-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_admin_user_photo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_user',
            name='user_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
