# Generated by Django 3.2.6 on 2021-08-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_admin_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_user',
            name='photo_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/admin_user'),
        ),
    ]
