# Generated by Django 3.2.6 on 2021-08-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_ads_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_table',
            name='photo_img',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='photos/ads_table'),
        ),
    ]
