# Generated by Django 3.2.6 on 2021-08-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
