# Generated by Django 3.2.6 on 2021-09-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_news',
            name='news_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='latest_news',
            name='news_type',
            field=models.CharField(default='latest', max_length=20),
        ),
    ]
