# Generated by Django 3.2.6 on 2021-09-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20210901_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_user',
        ),
    ]
