# Generated by Django 3.2.6 on 2021-09-01 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_delete_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest_news',
            name='news_id',
        ),
        migrations.AddField(
            model_name='antarastriya',
            name='Latest_news',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Latest_news_antarastriya', to='app.latest_news'),
        ),
        migrations.AddField(
            model_name='antarbarta',
            name='Latest_news',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Latest_news_antarbarta', to='app.latest_news'),
        ),
        migrations.AddField(
            model_name='bichar_lekh',
            name='Latest_news',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Latest_news_bichar_lekh', to='app.latest_news'),
        ),
        migrations.AddField(
            model_name='esthaniya',
            name='Latest_news',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Latest_news_esthaniya', to='app.latest_news'),
        ),
        migrations.AddField(
            model_name='grihaprista',
            name='date_time_picker',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='khelud',
            name='Latest_news',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Latest_news_khelud', to='app.latest_news'),
        ),
        migrations.AddField(
            model_name='manoranjan',
            name='Latest_news',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Latest_news_manoranjan', to='app.latest_news'),
        ),
        migrations.AddField(
            model_name='pradesh',
            name='Latest_news',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Latest_news_pradesh', to='app.latest_news'),
        ),
        migrations.AddField(
            model_name='sampadakiya',
            name='Latest_news',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Latest_news_sampadakiya', to='app.latest_news'),
        ),
        migrations.AddField(
            model_name='sandhiya',
            name='Latest_news',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Latest_news_sandhiya', to='app.latest_news'),
        ),
        migrations.AddField(
            model_name='suchanapraviti',
            name='Latest_news',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Latest_news_suchanapraviti', to='app.latest_news'),
        ),
    ]
